// 解析接口列表
export const parsingServices = [
    // ================= 通用解析接口 =================
    { name: "接口", url: "https://api.svip10.top/?id=2&url=", type: "通用解析", status: "unknown", latency: 0 }
  ];
  
  // 多语言文本
  export const translations = {
    zh: {
      appTitle: "视频解析助手",
      appSubtitle: "一键解析各大平台VIP视频",
      darkText: "暗色模式",
      lightText: "亮色模式",
      langText: "English",
      announcementText: "公告",
      urlTitle: "当前页面链接",
      fetchingUrl: "正在获取当前页面URL...",
      copyText: "复制",
      serviceTitle: "选择解析接口",
      randomText: "随机接口",
      randomDesc: "每次随机选择可用接口",
      parseText: "开始解析",
      footerText: "© 2025 视频解析助手 | 仅供学习交流使用",
      notificationText: "已复制到剪贴板",
      announcementTitle: "重要公告",
      onlineText: "在线",
      offlineText: "离线",
      allText: "全部",
      refreshText: "刷新接口状态",
      customTitle: "添加自定义接口",
      nameLabel: "接口名称",
      urlLabel: "接口URL",
      typeLabel: "接口类型",
      testText: "测试接口",
      addText: "添加接口",
      namePlaceholder: "接口名称",
      urlPlaceholder: "https://example.com/?url=",
      noServicesText: "没有匹配的接口",
      generalType: "通用解析",
      douyinType: "抖音/TikTok",
      multiType: "多平台万能",
      bilibiliType: "B站专用",
      platformType: "平台专用",
      overseasType: "海外加速",
      backupType: "备用接口",
      specialType: "特殊场景",
      
      announcementGreeting: "尊敬的插件用户：",
      announcementUpdate: "我们很高兴地宣布视频解析助手插件 v3.0 版本正式发布！本次更新带来了多项改进和新功能：",
      update1: "新增接口状态实时检测功能",
      update2: "支持自定义接口添加与管理",
      update3: "按类型分类展示接口",
      update4: "优化了接口选择体验",
      update5: "全新的现代化UI设计",
      tipsTitle: "使用提示",
      tip1: "1. 遇到解析失败时，请尝试切换其他接口",
      tip2: "2. 随机接口模式会自动选择当前可用性最好的解析服务",
      tip3: "3. 推荐使用暗色模式在夜间使用本插件",
      announcementFooter: "我们致力于为您提供最好的视频解析体验。如果您有任何问题或建议，请访问我们的",
      githubText: "GitHub页面",
      announcementFooter2: "提交反馈。",
      thanksText: "感谢您使用视频解析助手！",
      signature: "开发团队敬上"
    },
    en: {
      appTitle: "Video Parser Pro",
      appSubtitle: "VIP Video Parsing with One Click",
      darkText: "Dark Mode",
      lightText: "Light Mode",
      langText: "中文",
      announcementText: "Announcement",
      urlTitle: "Current Page URL",
      fetchingUrl: "Fetching current URL...",
      copyText: "Copy",
      serviceTitle: "Select Parsing Service",
      randomText: "Random Service",
      randomDesc: "Select a random service each time",
      parseText: "Parse Now",
      footerText: "© 2025 Video Parser Pro | For Educational Use Only",
      notificationText: "Copied to clipboard",
      announcementTitle: "Important Announcement",
      onlineText: "Online",
      offlineText: "Offline",
      allText: "All",
      refreshText: "Refresh Status",
      customTitle: "Add Custom Service",
      nameLabel: "Service Name",
      urlLabel: "Service URL",
      typeLabel: "Service Type",
      testText: "Test Service",
      addText: "Add Service",
      namePlaceholder: "Service name",
      urlPlaceholder: "https://example.com/?url=",
      noServicesText: "No matching services",
      generalType: "General",
      douyinType: "Douyin/TikTok",
      multiType: "Multi-platform",
      bilibiliType: "Bilibili",
      platformType: "Platform Specific",
      overseasType: "Overseas",
      backupType: "Backup",
      specialType: "Special Scenarios",
      
      announcementGreeting: "Dear plugin users:",
      announcementUpdate: "We are pleased to announce the official release of Video Parser Pro v3.0! This update brings multiple improvements and new features:",
      update1: "Added real-time service status detection",
      update2: "Support for custom service management",
      update3: "Services categorized by type",
      update4: "Improved service selection experience",
      update5: "Completely redesigned modern UI",
      tipsTitle: "Usage Tips",
      tip1: "1. If parsing fails, try switching to another service",
      tip2: "2. Random service mode selects the best available service",
      tip3: "3. Dark mode is recommended for night use",
      announcementFooter: "We are committed to providing the best video parsing experience. If you have any questions or suggestions, please visit our",
      githubText: "GitHub page",
      announcementFooter2: "to submit feedback.",
      thanksText: "Thank you for using Video Parser Pro!",
      signature: "Development Team"
    }
  };
